Add option to reading input files from one single yaml file
gnelissen/np-schedulability-analysis pull request #15
Opened 2024-03-07 16:01 UTC by porya-gohary

The main changes are:

1. [yaml-cpp](https://github.com/jbeder/yaml-cpp) added as a submodule to the project to parse yaml files
2. Project version updated to 2.2 in [CMakeLists.txt](https://github.com/gnelissen/np-schedulability-analysis/compare/master...porya-gohary:np-schedulability-analysis:add_yaml?expand=1#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a).
3. [CMakeLists.txt](https://github.com/gnelissen/np-schedulability-analysis/compare/master...porya-gohary:np-schedulability-analysis:add_yaml?expand=1#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a) updated to compile yaml-cpp library.
4. In [include/io.hpp](https://github.com/gnelissen/np-schedulability-analysis/compare/master...porya-gohary:np-schedulability-analysis:add_yaml?expand=1#diff-6a4ec05b747b2670559d897d45a42ce4650531740bad9dfdfb1f5983aae53363), two functions `parse_yaml_job_file` and `parse_yaml_dag_file` added to parse job set and their precedence.
5. In [include/io.hpp](https://github.com/gnelissen/np-schedulability-analysis/compare/master...porya-gohary:np-schedulability-analysis:add_yaml?expand=1#diff-6a4ec05b747b2670559d897d45a42ce4650531740bad9dfdfb1f5983aae53363), the old `parse_file` function, renamed to `parse_csv_job_file`.
6. All test cases in `src/tests` were refactored according to changes in 5.
7. Two existing examples `fig1a.csv` (with precedence constraint) and `global-fig.csv` also written in yaml format.

2024-03-07 17:34 UTC, porya-gohary commented
Please notice that in this implementation `yaml-cpp` is used as an integrated library from the source and is not used as an installed library. So after pulling the code, the submodule should also be downloaded using: `git submodule update --init --recursive`. This should be also mentioned in the `README.md`.

2024-03-13 13:15 UTC, porya-gohary commented
Now the successors of a job can be written in both compact and expanded formats.
In the compact format, dependencies are described as a sequence. For example:
`Successors: [[Int, Int], [Int, Int]]`
In the expanded format successors are explicitly mentioned as an array. For example:
```
Successors:
           - TaskID: Int
              JobID: Int
           - TaskID: Int
              JobID: Int
```

Note: Both of these syntaxes can be used in one single file together like the example in [examples/fig1a.yaml](https://github.com/gnelissen/np-schedulability-analysis/pull/15/commits/b8c66d235e0d1d7a9561c929c111e38efc34b3f4#diff-e7cf64ad6519ff7d87875298700196537f781a90c5ccbda8ab0cf70fd9f55dc4).

2024-03-18 13:12 UTC, gnelissen commented on include/io.hpp
> +					std::cout << "Job ID: " << j["Job ID"].as<unsigned long>() << std::endl;
seems like this line should be removed

2024-03-18 13:13 UTC, gnelissen commented on include/io.hpp
> +							std::cout << "Task ID: " << succ[0].as<unsigned long>() << std::endl;
same her. The cout should be removed

2024-03-18 13:46 UTC, gnelissen requested changes
clean io.hpp from unneeded printing

2024-03-18 13:46 UTC, gnelissen commented on include/io.hpp
a couple of cout must be cleaned

2024-03-18 14:28 UTC, merged