Changing Set_type from bool to bit for performance improvement
gnelissen/np-schedulability-analysis pull request #20
Opened 2024-09-04 14:09 UTC by porya-gohary

In our performance testing of the previous `Index_set` implementation using `std::vector<bool>` on Linux (GCC versions 11.4 and 12.3), we observed significantly higher runtime compared to MSVC on Windows.

To quantify the difference, we ran experiments on 200 task sets for a system with 4 cores on a server equipped with Red Hat 9.4 and AMD Rome 7H12 processors clocked at 2.6 GHz. The results showed that the previous implementation had an average runtime of 41.2 seconds and consumed 29.83 MB of memory. In contrast, the updated implementation, which replaces `bool` with bits using `std::vector<uint8_t>`, achieved an average runtime of just 0.678 seconds, with a slightly higher memory consumption of 30.22 MB.

2024-09-04 14:25 UTC, porya-gohary commented
Here are the profiles of two codes:

The profile of the original implementation (with `bool`):
![image](https://github.com/user-attachments/assets/8d307eaa-b710-4401-aafd-1c9ac8eaa578)


The profile after the change (with `bit`):
![image](https://github.com/user-attachments/assets/0f54bbc9-7374-4a89-ad7b-754c3f44c98a)

2024-09-04 14:55 UTC, gnelissen reviewed
I left minor comments in code

2024-09-04 14:55 UTC, gnelissen commented on include/index_set.hpp
> +				: the_set(std::max(from.the_set.size(), (idx / 8) + 1), 0)
no need to pass a const value to the constructor since it will be erased by the std::copy after anyway.  the constructor `the_set(std::max(from.the_set.size(), (idx / 8) + 1))` is enough.

2024-09-04 14:55 UTC, gnelissen commented on include/index_set.hpp
>  			}
could use binary operation on the uint8_t directly

2024-09-04 14:57 UTC, porya-gohary commented
Just as a side note. I dig the problem a bit deeper and it seems that `std::vector<bool>` has some known issues in the community and one of the issues is about sacrificing performance to save space. 
Please see the following references:

[1] Scott Meyers' Effective STL: 50 Specific Ways to Improve Your Use of the Standard Template Library (Addison-Wesley, 2001). In Item 18, titled "Avoid `vector<bool>`"
[[2] Is the use of std::vector<bool> objects acceptable, or should I use an alternative?](https://stackoverflow.com/questions/6781985/is-the-use-of-stdvectorbool-objects-in-c-acceptable-or-should-i-use-an-al)
[[3] Why is std::vector<bool> bad?](https://www.reddit.com/r/learnprogramming/comments/qb56c/c_why_is_vectorbool_bad/)

2024-09-04 15:04 UTC, porya-gohary commented
> Nitpick: there are a lot of whitespace changes that obscure what's actually being changed. Is that intentional?

I have reformatted the code to only use `tab` indents instead of `space` indents. But I am not sure if we want to have it in this commit.

@gnelissen Should I revert the indentation changes, or is it okay to include them in this commit?

2024-09-04 15:06 UTC, brandenburg commented
You should probably set a coding standard for the whole project and then make everything conform in one go. The downside is that `git blame` is going to become rather useless when trying to figure out why and when certain lines edited.

2024-09-04 15:09 UTC, brandenburg commented on include/index_set.hpp
> +		typedef std::vector<uint8_t> Set_type;
Question: since you are handcrafting bit vectors manually anyway, why not make a native machine word the base type? I.e., why bother with an 8-bit type when this will be running on 64-bit machines anyway?

2024-09-04 15:24 UTC, porya-gohary commented on include/index_set.hpp
> +		typedef std::vector<uint8_t> Set_type;
I initially chose to use 8-bit integers to minimize potential memory waste that could occur with 32 or 64-bit integers.

I'll change it to 64-bit and test it again.

2024-09-04 15:47 UTC, gnelissen commented
> I would have expected `vector<bool>` to compile to basically exactly what you have. Oh well, I guess not.

MSVC does the expected optimization. Before we merge anything in the main code, I will do comparison tests on Windows to see if we should consider to make the code platform specific.
@brandenburg if you have access to macOS, would you be able to compare the performance difference on that platform? We can share input files if needed

2024-09-04 17:00 UTC, brandenburg commented
Yeah, happy to run tests if you give me something to run.

2024-09-05 07:58 UTC, gnelissen approved these changes
The implementation is correct as far as I can tell. The method `is_subset_of()` could still be optimized by making binary operations at the word level instead of the bit. A test like 
```
for (std::size_t i = 0; i < the_set.size(); i++)
    if (the_set[i]>0 && (other.size()<=i || the_set[i] != the_set[i] & other[i]) )
        return false;
```
should do the trick

2024-09-05 08:23 UTC, gnelissen requested changes
the last change introduces a bug

2024-09-05 08:23 UTC, gnelissen commented on include/index_set.hpp
> +				// If the current set has more integers than the other set, it can't be a subset.
that is incorrect. If all elements in the_set is 0 than it is a subset whatever its size

2024-09-05 08:40 UTC, porya-gohary commented
> Yeah, happy to run tests if you give me something to run.

Thanks. Here are a couple of examples:
 - For a system with four cores (`-m 4`):
-- [jobset-log-uniform-discrete_94.csv](https://github.com/user-attachments/files/16886245/jobset-log-uniform-discrete_94.csv)
-- [jobset-uniform-discrete_29.csv](https://github.com/user-attachments/files/16886248/jobset-uniform-discrete_29.csv)
-- [jobset-log-uniform-discrete_69.csv](https://github.com/user-attachments/files/16886438/jobset-log-uniform-discrete_69.csv)
-- [jobset-log-uniform-discrete_73.csv](https://github.com/user-attachments/files/16886449/jobset-log-uniform-discrete_73.csv)

2024-09-05 08:42 UTC, gnelissen approved these changes

2024-09-05 10:17 UTC, gnelissen commented
> > Yeah, happy to run tests if you give me something to run.
> 
> Thanks. Here are a couple of examples:
> 
> * For a system with four cores (`-m 4`):
>   -- [jobset-log-uniform-discrete_94.csv](https://github.com/user-attachments/files/16886245/jobset-log-uniform-discrete_94.csv)
>   -- [jobset-uniform-discrete_29.csv](https://github.com/user-attachments/files/16886248/jobset-uniform-discrete_29.csv)
>   -- [jobset-log-uniform-discrete_69.csv](https://github.com/user-attachments/files/16886438/jobset-log-uniform-discrete_69.csv)
>   -- [jobset-log-uniform-discrete_73.csv](https://github.com/user-attachments/files/16886449/jobset-log-uniform-discrete_73.csv)

I confirm that, now that `uint64_t` are used runtime was also improved on Windows with MSVC, though not as significantly as with gcc on Linux (around 4x improvement on small examples on my laptop).

@nidhi2396 , who started the idea for the code re-organization, also confirmed that on our server running Linux, she experiences a 100X improvement in runtime when using this patch. 

This really shows how much the runtime of the rest of the code was improved, making the index_set the new bottleneck

2024-09-05 10:29 UTC, merged

2024-09-05 13:53 UTC, brandenburg commented
I ran [hyperfine](https://github.com/sharkdp/hyperfine) on my (old) iMac from 2017 (3,5 GHz Quad-Core Intel Core i5) under macOS 13.6 (22G120), using XCode's compiler," which identifies as AppleClang 15.0.0.15000100". 

Baseline bool vectors (commit 7569fa223ad3ffe8381ea7bd204f2bf05e7fe69a): 

```
Benchmark 1: ./nptest  ../benchmarks/jobset-log-uniform-discrete_69.csv
  Time (mean ± σ):     313.2 ms ±   3.1 ms    [User: 264.4 ms, System: 42.9 ms]
  Range (min … max):   307.6 ms … 317.9 ms    10 runs
 
Benchmark 2: ./nptest  ../benchmarks/jobset-log-uniform-discrete_73.csv
  Time (mean ± σ):      17.7 ms ±   0.9 ms    [User: 13.9 ms, System: 2.7 ms]
  Range (min … max):    16.4 ms …  22.5 ms    135 runs
 
Benchmark 3: ./nptest  ../benchmarks/jobset-log-uniform-discrete_94.csv
  Time (mean ± σ):      12.5 ms ±   1.8 ms    [User: 8.9 ms, System: 2.3 ms]
  Range (min … max):    10.7 ms …  21.4 ms    191 runs
 
Benchmark 4: ./nptest  ../benchmarks/jobset-uniform-discrete_29.csv
  Time (mean ± σ):     220.0 ms ±   5.6 ms    [User: 186.5 ms, System: 30.2 ms]
  Range (min … max):   210.1 ms … 231.0 ms    13 runs
```

Handcrafted bitfields (commit 2df64efcd22d6d7080bfe52206d58d36cfeaf49b):

```
Benchmark 1: ./nptest  ../benchmarks/jobset-log-uniform-discrete_69.csv
  Time (mean ± σ):     305.2 ms ±  16.0 ms    [User: 259.4 ms, System: 37.8 ms]
  Range (min … max):   288.9 ms … 344.7 ms    10 runs
 
Benchmark 2: ./nptest  ../benchmarks/jobset-log-uniform-discrete_73.csv
  Time (mean ± σ):      17.3 ms ±   0.5 ms    [User: 13.8 ms, System: 2.5 ms]
  Range (min … max):    16.3 ms …  19.4 ms    140 runs
 
Benchmark 3: ./nptest  ../benchmarks/jobset-log-uniform-discrete_94.csv
  Time (mean ± σ):      11.6 ms ±   0.5 ms    [User: 8.7 ms, System: 2.0 ms]
  Range (min … max):    10.6 ms …  13.5 ms    192 runs
 
Benchmark 4: ./nptest  ../benchmarks/jobset-uniform-discrete_29.csv
  Time (mean ± σ):     215.6 ms ±   4.7 ms    [User: 185.5 ms, System: 26.5 ms]
  Range (min … max):   206.1 ms … 220.1 ms    13 runs
```

Bottomline: it doesn't seem to make much of a difference.

2024-09-05 14:21 UTC, brandenburg commented
And here are the results for Apple's ARM silicon (M1 Max, same OS version, same compiler version):

```
Benchmark 1: SAG-bool-vector/build/nptest benchmarks/jobset-log-uniform-discrete_69.csv
  Time (mean ± σ):     139.7 ms ±   0.8 ms    [User: 123.9 ms, System: 14.5 ms]
  Range (min … max):   138.5 ms … 141.5 ms    20 runs
 
Benchmark 2: SAG-bitfield/build/nptest benchmarks/jobset-log-uniform-discrete_69.csv
  Time (mean ± σ):     139.2 ms ±   0.5 ms    [User: 123.8 ms, System: 14.3 ms]
  Range (min … max):   138.0 ms … 140.4 ms    21 runs
 
Summary
  SAG-bitfield/build/nptest benchmarks/jobset-log-uniform-discrete_69.csv ran
    1.00 ± 0.01 times faster than SAG-bool-vector/build/nptest benchmarks/jobset-log-uniform-discrete_69.csv
```

```
Benchmark 1: SAG-bool-vector/build/nptest benchmarks/jobset-log-uniform-discrete_73.csv
  Time (mean ± σ):       8.0 ms ±   0.2 ms    [User: 6.5 ms, System: 1.1 ms]
  Range (min … max):     7.8 ms …   8.9 ms    293 runs
 
Benchmark 2: SAG-bitfield/build/nptest benchmarks/jobset-log-uniform-discrete_73.csv
  Time (mean ± σ):       8.0 ms ±   0.1 ms    [User: 6.5 ms, System: 1.1 ms]
  Range (min … max):     7.7 ms …   8.7 ms    283 runs
 
Summary
  SAG-bitfield/build/nptest benchmarks/jobset-log-uniform-discrete_73.csv ran
    1.00 ± 0.03 times faster than SAG-bool-vector/build/nptest benchmarks/jobset-log-uniform-discrete_73.csv
```

```
Benchmark 1: SAG-bool-vector/build/nptest benchmarks/jobset-log-uniform-discrete_94.csv
  Time (mean ± σ):       5.2 ms ±   0.1 ms    [User: 4.0 ms, System: 0.9 ms]
  Range (min … max):     5.0 ms …   6.1 ms    410 runs
 
  Warning: Command took less than 5 ms to complete. Note that the results might be inaccurate because hyperfine can not calibrate the shell startup time much more precise than this limit. You can try to use the `-N`/`--shell=none` option to disable the shell completely.
 
Benchmark 2: SAG-bitfield/build/nptest benchmarks/jobset-log-uniform-discrete_94.csv
  Time (mean ± σ):       5.2 ms ±   0.1 ms    [User: 4.0 ms, System: 0.9 ms]
  Range (min … max):     4.9 ms …   5.9 ms    408 runs
 
  Warning: Command took less than 5 ms to complete. Note that the results might be inaccurate because hyperfine can not calibrate the shell startup time much more precise than this limit. You can try to use the `-N`/`--shell=none` option to disable the shell completely.
 
Summary
  SAG-bool-vector/build/nptest benchmarks/jobset-log-uniform-discrete_94.csv ran
    1.00 ± 0.03 times faster than SAG-bitfield/build/nptest benchmarks/jobset-log-uniform-discrete_94.csv
```

```
Benchmark 1: SAG-bool-vector/build/nptest benchmarks/jobset-uniform-discrete_29.csv
  Time (mean ± σ):      98.6 ms ±   0.8 ms    [User: 88.2 ms, System: 9.5 ms]
  Range (min … max):    97.8 ms … 101.4 ms    29 runs
 
Benchmark 2: SAG-bitfield/build/nptest benchmarks/jobset-uniform-discrete_29.csv
  Time (mean ± σ):      98.4 ms ±   0.4 ms    [User: 88.0 ms, System: 9.5 ms]
  Range (min … max):    97.6 ms …  99.5 ms    29 runs
 
Summary
  SAG-bitfield/build/nptest benchmarks/jobset-uniform-discrete_29.csv ran
    1.00 ± 0.01 times faster than SAG-bool-vector/build/nptest benchmarks/jobset-uniform-discrete_29.csv
```

It really makes no difference at all.

2024-09-05 18:46 UTC, gnelissen commented
all these results are good. That means that it improves performance on Linux and does not degrade performance on Windows and Mac. Conclusion: we do not have to maintain two different codes that are platform specific

2024-09-05 18:54 UTC, brandenburg commented
Yeah, but unfortunately these numbers here are bogus since I didn't notice that I should have specified `-m 4`. So these numbers only represent the "fast path" to an immediate deadline miss. Please refer to #26 for updated numbers (some of which I'm still collecting).