Bugs fixed and code readability improved
gnelissen/np-schedulability-analysis pull request #9
Opened 2023-06-21 12:10 UTC by porya-gohary

The summary of changes:

- `CMakeList.txt` updated to the latest version of the master branch.
- The labels of equations, algorithms, and lemma in the paper are added as comments to the `reduction_set.hpp` class to help code readability.
- Critical bug fixed in the implementation of Eq. 12 of the paper (while we have precedence constraint) in lines 401-438 of `reduction_set.hpp`. In the previous version, the code does not consider the precedence constraint and always uses Eq. 6 of the paper (without $\sum_{J_p \in ances(J_i) \cap J^M} C_p^{max}$).
- Minor bug fixed in preprocessing of DAGs in `precedence.hpp` that can affect some cases.
-  Unused functions are removed and files are reformatted. 
- One DAG task example (`dag_task.csv` and `dag_task.prec.csv`) is added to the example folder of the project to make the testing of the project with precedence constraints easier.

2023-06-21 12:17 UTC, brandenburg commented
To which paper do these equation numbers refer?

2023-06-21 12:26 UTC, porya-gohary commented
> To which paper do these equation numbers refer?

Equations label are matched with this paper: [Partial-order reduction in reachability-based response-time analyses of limited-preemptive DAG tasks](https://link.springer.com/article/10.1007/s11241-023-09398-x)

2023-06-21 12:46 UTC, brandenburg commented
Got it, thanks!

2023-06-21 15:06 UTC, gnelissen commented
Thanks Pourya. It correctly identified inconsistencies between the paper and the code.
To be noted that the "critical bug" did not impact the paper's experimental results because we have pj<pi* (via Eq. (11) and the tie breaking rule embedded in the "<" operatoron priorities) and rj^min<=ri^max <= s_i^(0) (via Algorithm 5) for all predecessors of Ji. Thus predecessors contributions are accounted for in Eq. (13). 
The actual bug is that Algorithm 5 was wrongly implemented (your minor bug), but the experimental setup in the paper enforced r_j^min = ri^min <= ri^max, thereby never triggering the minor bug.

2023-06-21 15:16 UTC, gnelissen requested changes
Correctly identified inconsistencies between the code and the paper [Partial-order reduction in reachability-based response-time analyses of limited-preemptive DAG tasks](https://link.springer.com/article/10.1007/s11241-023-09398-x).

As stated in the discussion, although not incorrect, the correction for the "critical bug" may not be required if the "minor bug on Alg. 5" is solved. The original implementation of `Time compute_si(...)` may be more efficient too. 
The new implementation of `Time compute_si(...)` may also add additional pessimism.

2023-06-21 15:16 UTC, gnelissen commented on include/uni/reduction_set.hpp
> +					while (!q.empty()) {
Did you consider the case where we have three jobs Ja, Jb and Jc with explicit precedence constraints Ja->Jb->Jc and Ja->Jc? It seems the contribution of Ja will be accounted twice when analyzing Jc in this case. 
That would be safe but pessimistic.

2023-06-21 16:43 UTC, porya-gohary commented on include/uni/reduction_set.hpp
> +					while (!q.empty()) {
Yes, this is pessimistic for the case you mentioned. I can fix it, but if equation 13 considers this part already, I remove it.

2023-06-24 12:07 UTC, gnelissen requested changes

2023-06-24 16:41 UTC, porya-gohary commented on include/precedence.hpp
> +			Job_precedence_set ancestors = preds;
This function is executed way before the calculation of the set of ancestors and topological order (See line 50 in `por_space.hpp`).
To move the `preprocess_jobs` function after the calculation of the set of ancestors the parameters in the constructor of `Por_state_space` should be changed, which then becomes inconsistent with other classes (also because of inheritance, it cannot be moved after line 120). Performance wise moving this after the calculation of ancestors is a good idea but for readability, I cannot say it helps.

2023-06-24 17:03 UTC, porya-gohary commented on include/uni/reduction_set.hpp
> +                    // ignore if we already considered this job as an ancestor in Eq. 12
> No need as it will be counted in Eq 13. See lines 443 and 444. All predecessors of i will always pass the test at those lines (sorry for the confusion during earlier communication)

> no need if it was never added to s_i^0

So if I am not mistaken we don't need the ancestor set anymore, right?

2023-06-30 06:46 UTC, gnelissen commented on include/uni/reduction_set.hpp
> +                    // ignore if we already considered this job as an ancestor in Eq. 12
correct

2023-10-20 10:28 UTC, gnelissen approved these changes

2023-10-20 10:28 UTC, merged